/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsSlugRouteImport } from './routes/products.$slug'
import { Route as PurchaseRequestsIndexRouteImport } from './routes/purchase-requests.index'
import { Route as PurchaseRequestsIdRouteImport } from './routes/purchase-requests.$id'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers.index'
import { Route as SuppliersIdRouteImport } from './routes/suppliers.$id'
import { Route as AuthenticatedBuyerDashboardRouteImport } from './routes/_authenticated/buyer.dashboard'
import { Route as AuthenticatedBuyerOrdersRouteImport } from './routes/_authenticated/buyer.orders'
import { Route as AuthenticatedBuyerRequestsIndexRouteImport } from './routes/_authenticated/buyer.requests.index'
import { Route as AuthenticatedBuyerRequestsIdRouteImport } from './routes/_authenticated/buyer.requests.$id'
import { Route as AuthenticatedBuyerRequestsNewRouteImport } from './routes/_authenticated/buyer.requests.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsIndexRoute = PurchaseRequestsIndexRouteImport.update({
  id: '/purchase-requests/',
  path: '/purchase-requests/',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchaseRequestsIdRoute = PurchaseRequestsIdRouteImport.update({
  id: '/purchase-requests/$id',
  path: '/purchase-requests/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIdRoute = SuppliersIdRouteImport.update({
  id: '/suppliers/$id',
  path: '/suppliers/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedBuyerDashboardRoute =
  AuthenticatedBuyerDashboardRouteImport.update({
    id: '/buyer/dashboard',
    path: '/buyer/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyerOrdersRoute =
  AuthenticatedBuyerOrdersRouteImport.update({
    id: '/buyer/orders',
    path: '/buyer/orders',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyerRequestsIndexRoute =
  AuthenticatedBuyerRequestsIndexRouteImport.update({
    id: '/buyer/requests/',
    path: '/buyer/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyerRequestsIdRoute =
  AuthenticatedBuyerRequestsIdRouteImport.update({
    id: '/buyer/requests/$id',
    path: '/buyer/requests/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBuyerRequestsNewRoute =
  AuthenticatedBuyerRequestsNewRouteImport.update({
    id: '/buyer/requests/new',
    path: '/buyer/requests/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/purchase-requests/$id': typeof PurchaseRequestsIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/products/': typeof ProductsIndexRoute
  '/purchase-requests/': typeof PurchaseRequestsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/buyer/dashboard': typeof AuthenticatedBuyerDashboardRoute
  '/buyer/orders': typeof AuthenticatedBuyerOrdersRoute
  '/buyer/requests/$id': typeof AuthenticatedBuyerRequestsIdRoute
  '/buyer/requests/new': typeof AuthenticatedBuyerRequestsNewRoute
  '/buyer/requests/': typeof AuthenticatedBuyerRequestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/purchase-requests/$id': typeof PurchaseRequestsIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/products': typeof ProductsIndexRoute
  '/purchase-requests': typeof PurchaseRequestsIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/buyer/dashboard': typeof AuthenticatedBuyerDashboardRoute
  '/buyer/orders': typeof AuthenticatedBuyerOrdersRoute
  '/buyer/requests/$id': typeof AuthenticatedBuyerRequestsIdRoute
  '/buyer/requests/new': typeof AuthenticatedBuyerRequestsNewRoute
  '/buyer/requests': typeof AuthenticatedBuyerRequestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/categories': typeof CategoriesRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/register': typeof RegisterRoute
  '/terms': typeof TermsRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/purchase-requests/$id': typeof PurchaseRequestsIdRoute
  '/suppliers/$id': typeof SuppliersIdRoute
  '/products/': typeof ProductsIndexRoute
  '/purchase-requests/': typeof PurchaseRequestsIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/_authenticated/buyer/dashboard': typeof AuthenticatedBuyerDashboardRoute
  '/_authenticated/buyer/orders': typeof AuthenticatedBuyerOrdersRoute
  '/_authenticated/buyer/requests/$id': typeof AuthenticatedBuyerRequestsIdRoute
  '/_authenticated/buyer/requests/new': typeof AuthenticatedBuyerRequestsNewRoute
  '/_authenticated/buyer/requests/': typeof AuthenticatedBuyerRequestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/products/$slug'
    | '/purchase-requests/$id'
    | '/suppliers/$id'
    | '/products/'
    | '/purchase-requests/'
    | '/suppliers/'
    | '/buyer/dashboard'
    | '/buyer/orders'
    | '/buyer/requests/$id'
    | '/buyer/requests/new'
    | '/buyer/requests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/categories'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/products/$slug'
    | '/purchase-requests/$id'
    | '/suppliers/$id'
    | '/products'
    | '/purchase-requests'
    | '/suppliers'
    | '/buyer/dashboard'
    | '/buyer/orders'
    | '/buyer/requests/$id'
    | '/buyer/requests/new'
    | '/buyer/requests'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/categories'
    | '/contact'
    | '/login'
    | '/privacy'
    | '/register'
    | '/terms'
    | '/products/$slug'
    | '/purchase-requests/$id'
    | '/suppliers/$id'
    | '/products/'
    | '/purchase-requests/'
    | '/suppliers/'
    | '/_authenticated/buyer/dashboard'
    | '/_authenticated/buyer/orders'
    | '/_authenticated/buyer/requests/$id'
    | '/_authenticated/buyer/requests/new'
    | '/_authenticated/buyer/requests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  CategoriesRoute: typeof CategoriesRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  RegisterRoute: typeof RegisterRoute
  TermsRoute: typeof TermsRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  PurchaseRequestsIdRoute: typeof PurchaseRequestsIdRoute
  SuppliersIdRoute: typeof SuppliersIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  PurchaseRequestsIndexRoute: typeof PurchaseRequestsIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/': {
      id: '/purchase-requests/'
      path: '/purchase-requests'
      fullPath: '/purchase-requests/'
      preLoaderRoute: typeof PurchaseRequestsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase-requests/$id': {
      id: '/purchase-requests/$id'
      path: '/purchase-requests/$id'
      fullPath: '/purchase-requests/$id'
      preLoaderRoute: typeof PurchaseRequestsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$id': {
      id: '/suppliers/$id'
      path: '/suppliers/$id'
      fullPath: '/suppliers/$id'
      preLoaderRoute: typeof SuppliersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/buyer/dashboard': {
      id: '/_authenticated/buyer/dashboard'
      path: '/buyer/dashboard'
      fullPath: '/buyer/dashboard'
      preLoaderRoute: typeof AuthenticatedBuyerDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer/orders': {
      id: '/_authenticated/buyer/orders'
      path: '/buyer/orders'
      fullPath: '/buyer/orders'
      preLoaderRoute: typeof AuthenticatedBuyerOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer/requests/': {
      id: '/_authenticated/buyer/requests/'
      path: '/buyer/requests'
      fullPath: '/buyer/requests/'
      preLoaderRoute: typeof AuthenticatedBuyerRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer/requests/$id': {
      id: '/_authenticated/buyer/requests/$id'
      path: '/buyer/requests/$id'
      fullPath: '/buyer/requests/$id'
      preLoaderRoute: typeof AuthenticatedBuyerRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buyer/requests/new': {
      id: '/_authenticated/buyer/requests/new'
      path: '/buyer/requests/new'
      fullPath: '/buyer/requests/new'
      preLoaderRoute: typeof AuthenticatedBuyerRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBuyerDashboardRoute: typeof AuthenticatedBuyerDashboardRoute
  AuthenticatedBuyerOrdersRoute: typeof AuthenticatedBuyerOrdersRoute
  AuthenticatedBuyerRequestsIdRoute: typeof AuthenticatedBuyerRequestsIdRoute
  AuthenticatedBuyerRequestsNewRoute: typeof AuthenticatedBuyerRequestsNewRoute
  AuthenticatedBuyerRequestsIndexRoute: typeof AuthenticatedBuyerRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBuyerDashboardRoute: AuthenticatedBuyerDashboardRoute,
  AuthenticatedBuyerOrdersRoute: AuthenticatedBuyerOrdersRoute,
  AuthenticatedBuyerRequestsIdRoute: AuthenticatedBuyerRequestsIdRoute,
  AuthenticatedBuyerRequestsNewRoute: AuthenticatedBuyerRequestsNewRoute,
  AuthenticatedBuyerRequestsIndexRoute: AuthenticatedBuyerRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  CategoriesRoute: CategoriesRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  RegisterRoute: RegisterRoute,
  TermsRoute: TermsRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  PurchaseRequestsIdRoute: PurchaseRequestsIdRoute,
  SuppliersIdRoute: SuppliersIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  PurchaseRequestsIndexRoute: PurchaseRequestsIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
